title: Kpable
theme: jekyll-theme-tactile
email: lhryenos@gmail.com
description: > 
  Portfolio of a Gameplay Programmer
twitter_username: Kpable
github_username:  Kpable

# Defaults
defaults:
  -
    scope:
      path: "" 
      type: "pages" 
    values:
      layout: "home"
  -
    scope:
      path: ""
      type: "posts"
    values:
      excerpt_separator: <!--excerpt_end-->    

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false