# Site settings
title: Lesther Reynoso
subtitle: Software Engineer
email: lhreynos@gmail.com
# baseurl: "/editorial-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://kpable.github.io/" # the base hostname & protocol for your site
images_url: /assets/:category
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/Kpable
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/kpable

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: page
      permalink: :categories/:title/
      excerpt_separator: <!--excerpt_end-->    

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false